export default{
    data:{
        p1:{
            platform: "Kodego",
            title: "SamOne Print Your Style",
            techStach: "HTML, CSS, Bootstrap",
            desc: "This is the first mini project required in the bootcamp. This site doesn't have any back end function.",
            img: "miniproject.png",
            github: "https://github.com/WhistnerRojas/samoneprints",
            demo: "https://whistnerrojas.github.io/samoneprints/index.html",
            projectBy: '',
        },
        p2:{
            platform: "Kodego",
            title: "You Dessert It!",
            techStach: "HTML, CSS, Bootstrap, JavaScript, API",
            desc:"This is the second mini project required in the bootcamp. This site doesn't have any back end function.",
            img: "miniProject2.png",
            github: "https://github.com/WhistnerRojas/youDessertIt",
            demo: "https://whistnerrojas.github.io/youDessertIt/",
            projectBy: '',
        },
        p3:{
            platform: "Kodego",
            title: "SwiftMoneyTor",
            techStach: "Node.js, React.js, Bootstrap, MUI, JavaScript, API, Laravel, AWS (ECS, EC3, & RDS), Github, Netlify, MySql",
            desc:"Capstone. This has functionality in it. This website aims to help MSE to better manage their business.",
            img: "capstone.png",
            github: "https://github.com/SwiftMoneyTor/SwiftMoneyTor",
            demo: "https://swiftmoneytorph.netlify.app/",
            projectBy: 'Ellen, Whistner, Therese',
        },
        p4:{
            platform: "Kodego",
            title: "Kodego Activities",
            techStach: "HTML, CSS, Bootstrap",
            desc:"Listed here are some of the activities we did while on the bootcamp.",
            img: "kodego.png",
            github: "https://github.com/WhistnerRojas/kodego-demo/tree/master",
            demo: "https://whistnerrojas.github.io/kodego-demo/",
            projectBy: 'Whistner',
        },
        p5:{
            platform: "Kodego",
            title: "Kodego Quiz | tik-tak-toe game",
            techStach: "React.js, Typescript, Bootstrap",
            desc:"This was one of the final quizes of Kodego.",
            img: "tiktaktoe.png",
            github: "https://github.com/WhistnerRojas/tictoctoe",
            demo: "https://tictoctoe-wiz.netlify.app/",
            projectBy: 'Whistner',
        },
        p6:{
            platform: "Kodego",
            title: "Kodego Quiz | API Bitcoin",
            techStach: "HTML, CSS, Javascript, API",
            desc:"API bitcoin is to display the rates of different crypto coins.",
            img: "apiCrypto.png",
            github: "https://github.com/WhistnerRojas/API-Bitcoin",
            demo: "https://whistnerrojas.github.io/API-Bitcoin/",
            projectBy: 'Whistner',
        },
        p7:{
            platform: "College",
            title: "GAA LMS",
            techStach: "HTML, CSS, PHP, MySql, PHPmyAdmin",
            desc:"Golden Achievers Academy LMS Features: Login/sign-up, learning module, teacher / student account, creating class, enrolling student to the class, creation of quiz and exam, randomize exam, upload/update profile picture, teacher / student account setting.",
            img: "gaa.png",
            github: "https://github.com/WhistnerRojas/gaa-LMS",
            demo: "",
            projectBy: 'Whistner and members',
        },
        p8:{
            platform: "Portfolio",
            title: "Personal Website",
            techStach: "Reactjs, TypeScript, Bootstrap, MUI, API",
            desc:"This is a website that aims to showcase my skills.",
            img: "portfolio.png",
            github: "https://github.com/WhistnerRojas/portfolio",
            demo: "https://whistner.netlify.app/",
            projectBy: "Whistner",
        },
        p9:{
            platform: "Tech Exam",
            title: "Expense Manager",
            techStach: "Laravel, MySQL, Vue, Bootstrap",
            desc:"This is my tech exam answer",
            img: "pbTechExam.png",
            github: "https://github.com/WhistnerRojas/ExpenseManager",
            demo: "",
            projectBy: 'Whistner',
        },
        p10:{
            platform: "Chat APP",
            title: "Simpla Chat APP",
            techStach: "HTML, CSS, JavaScript, MySQL, PHP",
            desc: "A simple Chat APP by Coding Nepal, Refactored by Whistner Rojas.",
            img: "",
            github: "https://github.com/WhistnerRojas/LearningPHP-loginSys",
            demo: "",
            projectBy: 'Whistner Rojas',
        },
    }
}